### ISSUE TITLE
review telegram

### ISSUE THREAD

**Issue by shevchuknine** [7denis7denis7/Task1.1#1]
визуально отлично!
_
https://github.com/7denis7denis7/Task1.1/blob/b3ccf2f0c2ea226c37e3f5ea237e290204c9481c/src/App.js#L29
поля key для реакта должны формироваться на основании данных, но не должны быть данными. т.е. ты можешь использовать id-шники, какие-то другие уникальные данные и т.д.. либо же, если знаешь, что сортировки в данных нет и кол-во данных не меняется (кол-во элементов в массиве), то можно использовать индексы массива
_
https://github.com/7denis7denis7/Task1.1/blob/b3ccf2f0c2ea226c37e3f5ea237e290204c9481c/src/App.js#L26
в реальных проектах это скорее всего будет строка в формате `20050809T183142 (YYYYMMDDThhmmss)` или подобном, прикрути это и у себя с приведением к красивому формату как уже реализовано
_
https://github.com/7denis7denis7/Task1.1/blob/b3ccf2f0c2ea226c37e3f5ea237e290204c9481c/src/components/Name/Name.jsx#L18-L20
это код к которому ты уже 99% не вернешься, так что смело удаляй поодбные комменты. на крайний случай, вся история есть в гите. это помогает хранить проект в чистоте

**Comment by shevchuknine** [comment]
https://github.com/7denis7denis7/Task1.1/blob/99500ef1e98ce2761f8960f112b9f0e499112ab3/src/components/Message/Message.jsx#L22-L24
я замечания оставляю в одном месте, но применяться они могут к нескольким местам в проекте. проверяй весь проект на повторения

**Comment by 7denis7denis7** [comment]
> https://github.com/7denis7denis7/Task1.1/blob/99500ef1e98ce2761f8960f112b9f0e499112ab3/src/components/Message/Message.jsx#L22-L24
> 
> 
> я замечания оставляю в одном месте, но применяться они могут к нескольким местам в проекте. проверяй весь проект на повторения

Извиняюсь, не внимательно просмотрел остальное в проекте, исправил
